### DISCUSSION TITLE
TB6612FNG

### DISCUSSION THREAD

**Discussion by mkonwerski** [makerspet/support#24] [General]
Great project. Unfortunately, I live in Europe, which makes the shipping costs for your products very high. A long time ago, I bought [waveshare](https://www.waveshare.com/wiki/General_Driver_for_Robots), which has been sitting in a box. I was really happy to read that KaiaAI/firmware supports TB6612FNG. Do you have an example configuration file for the TB6612FNG? I don't know how to set PWM-left, PWM-right

**Comment by kaiaai** [comment]
Hi Marcin, no worries. I'm trying to make the firmware work with all kinds of boards and drivers, so you can reuse your components.

Here is a schematic connecting TB6612FNG to ESP32 30-pin dev board.
![tb6612fng_esp32_kaiaai](https://github.com/user-attachments/assets/0395445f-7f0d-4343-aa1d-14720904130f)

In the schematic
- ESP32 GPIOs (configured as outputs) connect to TB6612FNG that drives two (left and right) DC brushed motors.
- ESP32  GPIOs (configured as inputs) also connect to (quadrature) motor encoders. Each quadrature motor encoder has 2 signals called A and B (or C1, C2 or something like that).

The choice of GPIO numbers to connect TB6612FNG and encoders is up to you - subject to ESP32 own limitations. See this https://makerspet.com/blog/esp32-gpio-limitations/ and this post https://makerspet.com/blog/esp32-s3-gpio-limitations/  for ESP32, ESP32S GPIO limitations.

Kaia.ai firmware has a `config.yaml` file where you specify your GPIO assignments https://github.com/kaiaai/firmware/blob/iron/kaiaai-esp32/data/config.yaml Kaia.ai firmware loads this file at boot time.

Here is an example of `config.yaml`. Be sure to keep the indents formatting to make sure the firmware parses `config.yaml` successfully. Check the Arduino Serial Monitor at boot time for any parsing errors.
```
#
# Board-specific assignments
#
board:
  manufacturer: makerspet.com
  model: MINI-BDC30P-BODY with BDC-30P
  version: v1.1.1
lidar:
  gpio:
    tx: 35
    rx: 27
    pwm: 13
    en: 32
led:
  system:
    driver:
      type: direct
      gpio: 2
      invert: false
button:
  boot:
    gpio: 0
    invert: true
monitor:
  gpio:
    tx: 1
motor:
  driver:
    type: IN1_IN2
  encoder:
    type: AB_QUAD
  left:
    encoder:
      gpio:
        a: 39
        b: 36
    driver:
      gpio:
        in1: 26
        in2: 25
  right:
    encoder:
      gpio:
        a: 17
        b: 16
    driver:
      gpio:
        in1: 23
        in2: 22
adc:
  battery:
    attenuation: 7.0
    gpio: 33
    voltage:
      full: 9.9
      empty: 7.2

#
# Peripherals configuration
#
lidar:
  model: LDROBOT LD14P
# model: NEATO XV11
# model: SLAMTEC RPLIDAR A1
# model: XIAOMI LDS02RR
# model: YDLIDAR SCL
# model: YDLIDAR X2
# model: YDLIDAR X2L
# model: YDLIDAR X3
# model: YDLIDAR X3 PRO
# model: 3IROBOTIX DELTA-2G
# model: 3IROBOTIX DELTA-2A 115200
# model: 3IROBOTIX DELTA-2A
# model: 3IROBOTIX DELTA-2B
# model: YDLIDAR X4 PRO
# model: YDLIDAR X4
  scan:
    freq:
      target: 5.0
monitor:
  baud: 115200
base:
  wheel:
    track: 0.105043
    diameter: 0.043
    accel:
      max: 2.0
motor:
  rpm:
# derated
    max: 180
  driver:
    pid:
      period: 0.03
      kp: 0.001
      ki: 0.003
      kd: 0
      kpm: 0
  encoder:
    ppr: 1035
```

In this example that works with TB6612FNG.

Here you can specify your board or DIY hardware name and version. Kaia.ai just prints out this information to Arduino Serial Monitor for identification purposes. The `#` hash character comments at the beginning of a text line acts as a comment.
```
#
# Board-specific assignments
#
board:
  manufacturer: makerspet.com
  model: MINI-BDC30P-BODY with BDC-30P
  version: v1.1.1
```

ESP32 GPIO assignments for the Lidar port. You can ignore this section if you don't use a Lidar. If your Lidar does not have some of the pins listed below, you can leave those assignments unchanged (they will be ignored) or commend those lines out.
```
lidar:
  gpio:
    tx: 35
    rx: 27
    pwm: 13
    en: 32
```

These lines configure the system LED GPIO. The configuration example below is specifically for 30-pin ESP32 DOIT DevKit v1 modules that have an integrated LED connected to GPIO2. Other ESP32 modules may have a different GPIO LED assignment, a different type of LED (serial instead of driven directly by the GPIO) or may not have an integrated LED at all. You can find and reuse examples for various ESP32, ESP32S3, ESP32E, Arduino ESP32S3 Nano boards here https://github.com/kaiaai/firmware/tree/iron/kaiaai-esp32/data
```
led:
  system:
    driver:
      type: direct
      gpio: 2
      invert: false
```

These lines assign a GPIO to the `BOOT` button for the 30-pin ESP32. The choice of this GPIO may vary across ESP32 modules and boards. See https://github.com/kaiaai/firmware/tree/iron/kaiaai-esp32/data for examples.
```
button:
  boot:
    gpio: 0
    invert: true
```

This is the GPIO assigned to the Arduino Serial Monitor (30-pin ESP32 boards in this example).
```
monitor:
  gpio:
    tx: 1
```

These lines specify the motor driver and motor encoder type. Simply speaking, Kaia.ai firmware supports two motor types:
- brushed DC with motor (driver type `IN1_IN2`) with quadrature encoder (encoder type `AB_QUAD`). This type of motor (popular low-cost N20, JGA25, etc.) have `MOTOR+` and `MOTOR-` motor inputs, directly driven usually by L298N, TB6612FNG or similar driver ICs that have `IN1` and `IN2` inputs. The quadrature encoder `AB_QUAD` has two outputs `A` and `B` (sometimes named `C1`, `C2` or similar).
- brushless DC motor with built-in ESC controller. Motors like this (driver type `PWM_CW`, encoder type `FG`) have `PWM` (speed) and `CW` (rotation direction) inputs and `FG` encoder output.

```
motor:
  driver:
    type: IN1_IN2
  encoder:
    type: AB_QUAD
```

Here is where you assign GPIO input to track the left motor quadrature encoder. If your motor is brushless with `fg` output, specify `fg
```
  left:
    encoder:
      gpio:
        a: 39
        b: 36
```

Here is where you assign GPIO outputs to your brushed motor driver IC (L298N, TB6612FNG, etc.) or to your brushless motor with built-in driver (using `fg: xx`).

If your motors don't work, rotate in the wrong direction or don't stop rotating - check the driver and encoder GPIO assignments. In particular, check if driver `in1` and `in2` GPIO assignments need to be swapped. Same goes for encoder `a` and `b` GPIO assignments.
```
    driver:
      gpio:
        in1: 26
        in2: 25
```

Set your GPIOs for the right motor.
```
  right:
    encoder:
      gpio:
        a: 17
        b: 16
    driver:
      gpio:
        in1: 23
        in2: 22
```

Optionally, assign a GPIO analog input to track the battery voltage. If your battery voltage higher than what ESP32 GPIO can handle, you can use a resistor divider to attenuate the battery voltage. For example, if you are using a 9V battery, you can make a resistor divider that divides the battery voltage 7x before feeding it to the ESP32 ADC GPIO input. The full and empty battery voltage settings help calculating the percentage of charge left in the battery.
```
adc:
  battery:
    attenuation: 7.0
    gpio: 33
    voltage:
      full: 9.9
      empty: 7.2
```

So far we have configured the board-related assignments. The rest of the file configures the robot-related parameters.

Choose your Lidar from the list of supported sensors and set the desired scan speed (if supported by firmware and your Lidar). If you are not using a Lidar, just leave this section unchanged.
```
#
# Peripherals configuration
#
lidar:
  model: LDROBOT LD14P
# model: NEATO XV11
# model: SLAMTEC RPLIDAR A1
# model: XIAOMI LDS02RR
# model: YDLIDAR SCL
# model: YDLIDAR X2
# model: YDLIDAR X2L
# model: YDLIDAR X3
# model: YDLIDAR X3 PRO
# model: 3IROBOTIX DELTA-2G
# model: 3IROBOTIX DELTA-2A 115200
# model: 3IROBOTIX DELTA-2A
# model: 3IROBOTIX DELTA-2B
# model: YDLIDAR X4 PRO
# model: YDLIDAR X4
  scan:
    freq:
      target: 5.0
```

Set the Arduino Serial Monitor baud rate.
```
monitor:
  baud: 115200
```

Distance between your wheels. More specifically, it is the distance between the midpoints of your tires.
```
base:
  wheel:
    track: 0.105043
```

Your outer wheel (tire) diameter.
```
    diameter: 0.043
```

Your robot's maximum allowed acceleration. For example
- increase the acceleration if your robot motors and power supply can handle the load
- decrease the max acceleration if
  - your robot wheels slip
  - your motors are not powerful enough (for the given robot's weight) to achieve the max acceleration
  - your motor driver or motor power supply cannot supply enough current
```
    accel:
      max: 2.0
```

Your motor max RPM taken from your motor's datasheet, derated (i.e. multiplied by ~0.9). The derating factor is necessary because actual max RPM varies from motor to motor, so letting both motors run at their max RPM often causes the robot veer off the straight path.
```
motor:
  rpm:
# derated
    max: 180
```

Kaia.ai firmware controls motors using a PID controller. Set the PID controller coefficients here. Check these settings if your motors lag or oscillate. `period` is how often the PID gets updated. `kp`, `ki`, `kd` and `kpm` are the proportional (AKA proportional-on-error), integral, derivative and proportional-on-measurement gain coefficients respectively. PID tuning is a topic worth a separate post.
```
  driver:
    pid:
      period: 0.03
      kp: 0.001
      ki: 0.003
      kd: 0
      kpm: 0
```

Lastly, `ppr` is the number of pulses the motor encoder outputs per one rotation of the motors shaft (i.e. the motor gearbox output).
```
  encoder:
    ppr: 1035
```

**Comment by mkonwerski** [comment]
Thank you for this description, I have a suggestion to add it to the README.

Unfortunately, I don't understand how to adjust the configuration file to support the TB6612FNG.

The manufacturer provides the GPIO mapping in their examples:

```
// Encoder A pin definition
const uint16_t AENCA = 35; // Encoder A input A_C2(B)
const uint16_t AENCB = 34; // Encoder A input A_C1(A)

// Motor A
const uint16_t AIN1 = 21; // Motor A input 1 Green
const uint16_t AIN2 = 17; // Motor A input 2 Brown
                     **const uint16_t PWMA = 25; // Motor A PWM control Orange**

// Encoder B pin definition
const uint16_t BENCA = 27; // Encoder B input B_C1(A)
const uint16_t BENCB = 16; // Encoder B input B_C2(B)

// Motor B
const uint16_t BIN1 = 22; // Motor B input 1 Yellow
const uint16_t BIN2 = 23; // Motor B input 2 Purple
                    **const uint16_t PWMB = 26; // Motor B PWM control White**
```
I provided the above data in the configuration file. 

```monitor:
  gpio:
    tx: 1
motor:
  driver:
    type: IN1_IN2
  encoder:
    type: AB_QUAD
  left:
    encoder:
      gpio:
        a: 27
        b: 16
    driver:
      gpio:
        in1: 22
        in2: 23
  right:
    encoder:
      gpio:
        a: 35
        b: 34
    driver:
      gpio:
        in1: 21
        in2: 17
```


This configuration allows reading data from the encoder but does not allow the motors to start. This happens because your configuration file is missing definitions for PWMA and PWMB. On your schematic, you connected PWMA and PWMB to +5V.

**Comment by kaiaai** [comment]
I see, you need to drive PWMA/B constant high. I can add support for driving GPIO constant high this to `config.yaml` in the next release.

I the meantime, how about adding this code at the very beginning of setup()
```
  digitalWrite(25, HIGH); // const uint16_t PWMA = 25; // Motor A PWM control Orange**
  digitalWrite(26, HIGH); // const uint16_t PWMB = 26; // Motor B PWM control White**
```

**Comment by mkonwerski** [comment]
PWMA/B is used for speed control. As expected, when we set a high level on the pin, the motors will spin at a constant maximum speed.

I analyzed your code and, as I understand it, in my case, I should set MOT_DRIVER_PWM_CW (type: PWM_CW)?

motors.h:
```
void setMotorPWM(MotorController *motor_controller, float pwm) {
  bool is_right = motor_controller == &motorRight;
  
  uint8_t pwm_channel = is_right ? cfg.MOT_PWM_RIGHT_CHANNEL : cfg.MOT_PWM_LEFT_CHANNEL;
  int max_pwm = (1<<cfg.MOT_PWM_BITS) - 1;
  uint8_t cw_pin = is_right ? cfg.mot_right_drv_gpio_in2_cw : cfg.mot_left_drv_gpio_in2_cw;
  uint8_t in1_pin = is_right ? cfg.mot_right_drv_gpio_in1_pwm : cfg.mot_left_drv_gpio_in1_pwm;
  uint8_t in2_pin = is_right ? cfg.mot_right_drv_gpio_in2_cw : cfg.mot_left_drv_gpio_in2_cw;

  pwm = pwm > 1 ? 1 : pwm;
  int pwm_magnitude = round(max_pwm*(1 - abs(pwm)));
  byte cw_value = pwm >= 0 ? LOW : HIGH;

  switch(motorDriverType) {
    case MOT_DRIVER_PWM_CW:
      ledcWrite(pwm_channel, pwm_magnitude);
      digitalWrite (cw_pin, cw_value); //pwm >= 0 ? LOW : HIGH);
      break;
```

Should I add the cw field to the configuration file?
```
motor:
  driver:
    type: PWM_CW
  encoder:
    type: AB_QUAD
  left:
    encoder:
      gpio:
        a: 27
        b: 16
    driver:
      gpio:
        cw: 25
        in1: 22
        in2: 23
  right:
    encoder:
      gpio:
        a: 35
        b: 34
    driver:
      gpio:
        cw: 25
        in1: 21
        in2: 17
```
