### DISCUSSION TITLE
Can i use LM393 encoder as the encoder

### DISCUSSION THREAD

**Discussion by NanonbulidZ** [makerspet/support#35] [Support Q&A]
is there anyway to use LM393 encoder and if yes what encoder type do i have to use? in the config.yaml
https://www.ebay.co.uk/itm/232516162353

**Comment by kaiaai** [comment]
Hello,

yes, generally speaking, you can use LM393 opamp as an encoder with these settings in the ```config.yaml```. 


For example, if the left wheel's LM393 output is connected to ESP32 GPIO 39 and the right wheel's LM393 to ESP32 GPIO 17:


```
motor:
  driver:
    type: FG
  left:
    encoder:
      gpio:
        fg: 39
  right:
    encoder:
      gpio:
        fg: 17
```

That said, I don't recommend using a slotted encoder because its resolution is too low - on the order of a few tens of pulses per rotation.

This is not enough PPR pulses-per-revolution for the PID motor controller to measure wheels RPM reliably at a low speed. The robot's wheels will twitch at low speeds. An acceptable PPR should be close to a thousand.

**Reply by NanonbulidZ** [reply]
thank you

**Reply by NanonbulidZ** [reply]
also i cant seem to switch to RPLIDAR A1 becuase when i switch it in the config.yaml it keep using the default lidar

**Reply by kaiaai** [reply]
Please make sure you've read this post how to change the Lidar https://makerspet.com/blog/connect-ydlidar-x3-to-makerspet-esp32-boards/

Also, please post your config.yaml and ESP32 serial boot dump copy from the Arduino serial monitor.

**Reply by NanonbulidZ** [reply]
will in the future will you add support for RPLIDAR c1?

**Reply by kaiaai** [reply]
Eventually, yes. That said, I don't have a RPLIDAR C1 for debug for now.

**Reply by NanonbulidZ** [reply]
startLIDAR() result: Device Info error
Is the LiDAR connected to ESP32 and powered up?
i have tired it but this happened and the lidar wont spin

**Reply by NanonbulidZ** [reply]
also this is my config.yaml

board:
  manufacturer: Nanon
  model: RBC
  version: v0.0.1

lidar:
  gpio:
    tx: 16
    rx: 17
    pwm: 13
    en: 25

led:
  system:
    driver:
      type: direct
      gpio: 2
      invert: false

button:
  boot:
    gpio: 0
    invert: true

monitor:
  gpio:
    tx: 1

motor:
  driver:
    type: IN1_IN2
  encoder:
    type: FG
  left:
    encoder:
      gpio:
        fg: 32
    driver:
      gpio:
        in1: 26
        in2: 25
  right:
    encoder:
      gpio:
        fg: 34

    driver:
      gpio:
        in1: 23
        in2: 22

adc:
  battery:
    attenuation: 7.0
    gpio: 33
    voltage:
      full: 9.9
      empty: 7.2

lidar:
# model: LDROBOT LD14P
# model: NEATO XV11
 model: SLAMTEC RPLIDAR A1
# model: XIAOMI LDS02RR
# model: YDLIDAR SCL
# model: YDLIDAR X2
# model: YDLIDAR X2L
# model: YDLIDAR X3
# model: YDLIDAR X3 PRO
# model: 3IROBOTIX DELTA-2G
# model: 3IROBOTIX DELTA-2A 115200
# model: 3IROBOTIX DELTA-2A
# model: 3IROBOTIX DELTA-2B
# model: YDLIDAR X4 PRO
# model: YDLIDAR X4
  scan:
    freq:
      target: 5.0
monitor:
  baud: 115200
base:
  wheel:
    track: 0.105043
    diameter: 0.043
    accel:
      max: 2.0
motor:
  rpm:
# derated
    max: 180
  driver:
    pid:
      period: 0.03
      kp: 0.001
      ki: 0.003
      kd: 0
      kpm: 0
  encoder:
    ppr: 1035

**Reply by NanonbulidZ** [reply]
```

board:
  manufacturer: Nanon
  model: RBC
  version: v0.0.1

lidar:
  gpio:
    tx: 16
    rx: 17
    pwm: 13
    en: 25

led:
  system:
    driver:
      type: direct
      gpio: 2
      invert: false

button:
  boot:
    gpio: 0
    invert: true

monitor:
  gpio:
    tx: 1

motor:
  driver:
    type: IN1_IN2
  encoder:
    type: FG
  left:
    encoder:
      gpio:
        fg: 32
    driver:
      gpio:
        in1: 26
        in2: 25
  right:
    encoder:
      gpio:
        fg: 34

    driver:
      gpio:
        in1: 23
        in2: 22

adc:
  battery:
    attenuation: 7.0
    gpio: 33
    voltage:
      full: 9.9
      empty: 7.2

lidar:
# model: LDROBOT LD14P
# model: NEATO XV11
 model: SLAMTEC RPLIDAR A1
# model: XIAOMI LDS02RR
# model: YDLIDAR SCL
# model: YDLIDAR X2
# model: YDLIDAR X2L
# model: YDLIDAR X3
# model: YDLIDAR X3 PRO
# model: 3IROBOTIX DELTA-2G
# model: 3IROBOTIX DELTA-2A 115200
# model: 3IROBOTIX DELTA-2A
# model: 3IROBOTIX DELTA-2B
# model: YDLIDAR X4 PRO
# model: YDLIDAR X4
  scan:
    freq:
      target: 5.0
monitor:
  baud: 115200
base:
  wheel:
    track: 0.105043
    diameter: 0.043
    accel:
      max: 2.0
motor:
  rpm:
# derated
    max: 180
  driver:
    pid:
      period: 0.03
      kp: 0.001
      ki: 0.003
      kd: 0
      kpm: 0
  encoder:
    ppr: 1035
```
